ALTER TABLE DEPARTMENT
ADD CONSTRAINT ManagerFK FOREIGN KEY (ManagerID)
    REFERENCES EMPLOYEE(EmployeeID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT ManagerREF FOREIGN KEY(ManagerID)
    REFERENCES EMPLOYEE(EmployeeID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT DepartmentFK FOREIGN KEY(DepartmentName)
    REFERENCES DEPARTMENT(DepartmentName)
    ON UPDATE CASCADE
    ON DELETE CASCADE;