CREATE TABLE UNIONTABLE (
    UnionID int NOT NULL IDENTITY(1,1),
    Name VARCHAR(255)
    CONSTRAINT UnionPK PRIMARY KEY (UnionID)
);

CREATE TABLE OPERATOR (
    EmployeeID int NOT NULL,
    UnionID int NOT NULL
    CONSTRAINT OperatorFK FOREIGN KEY (UnionID)
        REFERENCES UNIONTABLE(UnionID)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT OperatorPK PRIMARY KEY (EmployeeID),
    CONSTRAINT OperatorPKFK FOREIGN KEY (EmployeeID)
        REFERENCES EMPLOYEE(EmployeeID)
            ON UPDATE CASCADE
            ON DELETE CASCADE
);